
MODULE oad_intrinsics
use OAD_active
use w2f__types
IMPLICIT NONE
SAVE
!
!     **** Statements ****
!
END MODULE

MODULE var
use OAD_active
use w2f__types
IMPLICIT NONE
SAVE
!
!     **** Global Variables & Derived Type Definitions ****
!
REAL(w2f__8) QUADPARAMS(1 : 3)
type(active) :: X
type(active) :: Y
type(active) :: Z
!
!     **** Statements ****
!
END MODULE
!#########################################################
! This file is part of OpenAD released under the LGPL.   #
! The full COPYRIGHT notice can be found in the top      #
! level directory of the OpenAD distribution             #
!#########################################################

SUBROUTINE calc_curve()
    use OAD_tape
    use OAD_rev

! original arguments get inserted before version
!         ! and declared here together with all local variables
!         ! generated by xaifBooster

use OAD_active
use w2f__types
use oad_intrinsics
use var
use oad_intrinsics
use var
use oad_intrinsics
use var
IMPLICIT NONE
!
!     **** Local Variables and Functions ****
!
REAL(w2f__8) OpenAD_Symbol_0
REAL(w2f__8) OpenAD_Symbol_1
REAL(w2f__8) OpenAD_Symbol_2
REAL(w2f__8) OpenAD_acc_0
REAL(w2f__8) OpenAD_aux_0
REAL(w2f__8) OpenAD_lin_0
REAL(w2f__8) OpenAD_lin_1
REAL(w2f__8) OpenAD_lin_2
REAL(w2f__8) OpenAD_lin_3
!
!     **** Top Level Pragmas ****
!
!$OPENAD INDEPENDENT(X)
!$OPENAD DEPENDENT(Y)
!$OPENAD DEPENDENT(Z)
!
!     **** Statements ****
!


    integer iaddr
    external iaddr

   if (our_rev_mode%plain) then
! original function
Y%v = (QUADPARAMS(3)+QUADPARAMS(1)*(X%v**2)+QUADPARAMS(2)*X%v)
Z%v = (QUADPARAMS(1)*Y%v)
    end if
    if (our_rev_mode%tape) then
! taping
OpenAD_aux_0 = (X%v**2)
OpenAD_lin_1 = (2*(X%v**(2-INT(1_w2f__i8))))
OpenAD_lin_0 = QUADPARAMS(1)
OpenAD_lin_2 = QUADPARAMS(2)
Y%v = (QUADPARAMS(3)+QUADPARAMS(1)*OpenAD_aux_0+QUADPARAMS(2)*X%v)
OpenAD_lin_3 = QUADPARAMS(1)
Z%v = (QUADPARAMS(1)*Y%v)
OpenAD_acc_0 = (OpenAD_lin_1*OpenAD_lin_0)
double_tape(double_tape_pointer) = OpenAD_lin_2
double_tape_pointer = double_tape_pointer+1
double_tape(double_tape_pointer) = OpenAD_acc_0
double_tape_pointer = double_tape_pointer+1
double_tape(double_tape_pointer) = OpenAD_lin_3
double_tape_pointer = double_tape_pointer+1
    end if
    if (our_rev_mode%adjoint) then
! adjoint
double_tape_pointer = double_tape_pointer-1
OpenAD_Symbol_0 = double_tape(double_tape_pointer)
double_tape_pointer = double_tape_pointer-1
OpenAD_Symbol_1 = double_tape(double_tape_pointer)
double_tape_pointer = double_tape_pointer-1
OpenAD_Symbol_2 = double_tape(double_tape_pointer)
Y%d = Y%d+Z%d*(OpenAD_Symbol_0)
Z%d = 0.0d0
X%d = X%d+Y%d*(OpenAD_Symbol_1)
X%d = X%d+Y%d*(OpenAD_Symbol_2)
!Y%d = 0.0d0
    end if
  end subroutine calc_curve
